spring.application.name=E-commerceWebsite

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

spring.datasource.url=jdbc:postgresql://localhost:5432/Shopnexus-Ecommerce Store
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


logging.level.org.springframework=DEBUG
#logging.level.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.harshadcodes.EcommerceWebsite=DEBUG

security.secretKey=jdhrelafvalhafjriotruiaqalbdbvhagruyalvhjbadlfgudalbaldhjfwiurfbhalb
security.expirationDate=P1D
security.jwtCookie=auth_cookie

razorpay.key=${RAZORPAY_KEY}
razorpay.secret=${RAZORPAY_SECRET}

cloudinary_url=${CLOUDINARY_URL}

frontend.url=http://localhost:5173/
